---

- name: create the /export directory
  file:
    path: /export
    state: directory
    recurse: yes
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"

- name: download bgruening/docker-galaxy-stable
  git:
    repo: "https://github.com/bgruening/docker-galaxy-stable.git"
    dest: "{{ dgs_dir }}"
    version: "{{ dgs_branch }}"
  become_user: "{{ docker_user }}"

- name: build dgs-compose images
  command: "./build-orchestration-images.sh --no-push --condor --grafana --slurm --k8s"
  args:
    chdir: "{{ dgs_dir }}/compose"
  become_user: "{{ docker_user }}"
  when: not no_build

- name: pull dgs-compose images
  command: "./build-orchestration-images.sh --no-build --condor --grafana --slurm"
  args:
    chdir: "{{ dgs_dir }}/compose"
  become_user: "{{ docker_user }}"
  when: no_build

- name: get dgs env variables
  command: "sed 's/export //g' {{ dgs_dir }}/compose/tags-for-compose-to-source.sh"
  register: dgs_env

- name: add dgs env variables to /etc/environment
  lineinfile:
    line: "{{ item }}"
    path: "/etc/environment"
  with_items: "{{ dgs_env.stdout_lines }}"

- name: link .env
  file:
    src: "{{ dgs_dir }}/compose/.env_slurm"
    dest: "{{ dgs_dir }}/compose/.env"
    state: link
  become_user: "{{ docker_user }}"

- name: docker-compose up -d
  command: "docker-compose up -d"
  args:
    chdir: "{{ dgs_dir }}/compose"
  become_user: "{{ docker_user }}"
