---

- name: apt install packages for SNI verification
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - python-pip
      - python-openssl
      - python-pyasn1

- name: pip install package for SNI verification
  pip:
    name: ndg-httpsclient
    state: latest

- name: set docker users subuid range
  lineinfile:
    path: /etc/subuid
    state: present
    line: "{{ docker_user }}:{{ docker_id }}:65536"

- name: set docker users subgid range
  lineinfile:
    path: /etc/subgid
    state: present
    line: "{{ docker_user }}:{{ docker_id }}:65536"
- name: install rootless dependencies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - golang-go
      - uidmap

- name: download https://get.docker.com/rootless
  get_url:
    url: https://get.docker.com/rootless
    dest: "/home/{{ docker_user }}/get-docker-rootless.sh"
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: 0770

- name: run get-docker-rootless.sh
  command: "sh /home/{{ docker_user }}/get-docker-rootless.sh"
  args:
    chdir: "/home/{{ docker_user }}/"
  become_user: "{{ docker_user }}"

# at this point rootless files are in /home/{{ docker_user }}/bin
