---
# os task

# disabled for init travis testing
# - name: update all packages
#   apt:
#     name: "*"
#     update_cache: true
#     state: latest

- name: add docker group
  group:
    name: "{{ docker_user }}"
    gid: "{{ docker_id }}"

- name: add docker users
  user:
    name: "{{ docker_user }}"
    uid: "{{ docker_id }}"
    group: "{{ docker_id }}"
