---
# os task

- name: update all packages
  apt:
    name: "*"
    state: latest
    force_apt_get: yes
    update_cache: yes

- name: install access control lists
  apt:
    name: "acl"
    state: latest

- name: add docker group
  group:
    name: "{{ docker_user }}"
    gid: "{{ docker_id }}"

- name: add docker users
  user:
    name: "{{ docker_user }}"
    uid: "{{ docker_id }}"
    group: "{{ docker_id }}"
    groups: docker
