---

- name: apt install packages for SNI verification
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - python-pip
      - python-openssl
      - python-pyasn1

- name: pip install package for SNI verification
  pip:
    name: ndg-httpsclient
    state: latest

- name: set docker_user subuid range
  lineinfile:
    path: /etc/subuid
    state: present
    line: "{{ docker_user }}:{{ docker_id }}:65536"

- name: set docker_user subgid range
  lineinfile:
    path: /etc/subgid
    state: present
    line: "{{ docker_user }}:{{ docker_id }}:65536"

- name: install usernetes dependencies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - golang-go
      - uidmap

- name: download usernetes
  unarchive:
    src: https://github.com/rootless-containers/usernetes/archive/v20190212.0.tar.gz
    remote_src: yes
    dest: "/home/{{ docker_user }}/usernetes"
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: 0770
